<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Countries extends Model
{
    protected $table = "countries";
    protected $primaryKey = "idCountry";
    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function(Countries $toDelete){
            $locations = Locations::all()->where('idCountry','=',$toDelete->idCountry);
            if($locations->count()>0){
                foreach ($locations as $location){
                    $location->delete();
                }
            }
        });
    }
}
