<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Offers extends Model
{
    protected $table = "offers";
    protected $primaryKey = "idOffer";
    public $timestamps = false;

    public function country(){
        return $this->hasOne("App\Countries","idCountry","idCountry");
    }

    public function location(){
        return $this->hasOne("App\Locations","idLocation","idLocation");
    }

    public function season(){
        return $this->hasOne("App\Seasons","idSeason","idSeason");
    }

    public function picture(){
        return $this->hasOne('App\Pictures','idPicture','idPicture');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleted(function (Offers $toDelete){
            $picture = Pictures::find($toDelete->idPicture);
            $picture->delete();
        });
    }
}
