<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\File;

class Pictures extends Model
{
    protected $table = "pictures";
    protected $primaryKey = "idPicture";
    public $timestamps = false;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleted(function(Pictures $toDelete){
            File::delete(public_path().$toDelete->src);
        });
    }
}
