<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slides extends Model
{
    protected $table = "slides";
    protected $primaryKey = "idSlide";
    public $timestamps = false;

    public function picture(){
        return $this->hasOne('App\Pictures','idPicture','idPicture');
    }

    public static function boot(){
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleted(function (Slides $toDelete){
            $picture = Pictures::find($toDelete->idPicture);
            $picture->delete();
        });
    }
}
